---

- name: Gather OS specific install file
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}.yml"

- name: Download OS image
  get_url:
    url: "{{ vm_cloud_image }}"
    dest: "{{ dest_images_dir }}"
    force: no

# TODO: Replace shell command to qemu-img module
# Create 6 Disks (4 OSDs and 2 Journals)
- name: Create VM disks that will be used as OSD
  shell: "qemu-img create -f qcow2 {{ item[1]['src'] }} {{ item[1]['size'] }} "
  with_subelements:
    - "{{ vms }}"
    - osds

- name: Create VM disks that will be used as Journal
  shell: "qemu-img create -f qcow2 {{ item[1]['src'] }} {{ item[1]['size'] }} "
  with_subelements:
    - "{{ vms }}"
    - journal

# - name: Create cloud-config file
#   shell: echo 0
#
# - name: Create VMs...
#   shell: echo 0
#
- name: Create XML VMs templates
  template:
    src: templates/test_xml.j2
    dest: xml_templates/{{ item['key'] }}.txt
  with_dict:
    - "{{ vms }}"
